"""Static data constants for insight_extractor."""

from __future__ import annotations

from insight_extractor.config import PatternLabel

type RegexPatternDict = dict[str, str]
type KeywordList = list[str]

THREAD_SEEDS: KeywordList = [
    THREAD_SEEDS: KeywordList = [
    # Ransomware / threat intel
    "ransomware",
    "nitrogen",
    "foxconn",
    "ESXi",
    "conti",
    "ALPHV",
    "blackcat",
    "RaaS",
    "double extortion",
    "supply chain",
    "data breach",
    "exfiltration",
    "payload",
    "loader",
    "YARA",
    "veeam",
    "watchtowr",
    "CVE",
    # OSINT / identity
    "OSINT",
    "data broker",
    "NPD",
    "national public data",
    "SSN",
    "dox",
    "facial recognition",
    "biometric",
    "SIM swap",
    "credential reset",
    "identity theft",
    "breach data",
    # CG
    cgfixit
    grady
    cg
    Atlanta
    Georgia
    # CyClaw / AI infra
    "CyClaw",
    "LangGraph",
    "ChromaDB",
    "BM25",
    "RRF",
    "RAG",
    "soul",
    "personality",
    "sanitizer",
    "telemetry",
    "offline",
    "BERT",
    "embedding",
    "semantic search",
    "hybrid retrieval",
    # InfoSec / general
    "zero-day",
    "exploit",
    "phishing",
    "malware",
    "APT",
    "threat actor",
    "lateral movement",
    "privilege escalation",
    "encryption",
    "decryption",
    "public key",
    "private key",
    "cryptographic",
    # Technology / infrastructure
    "artificial intelligence",
    "machine learning",
    "generative AI",
    "large language model",
    "deepfake",
    "automation",
    "algorithm",
    "cloud computing",
    "data center",
    "database",
    "API",
    "open source",
    "software update",
    "vulnerability",
    "patch",
    "authentication",
    "authorization",
    "access control",
    "multi-factor authentication",
    "password",
    "credential",
    "firewall",
    "endpoint",
    "network security",
    "privacy",
    "surveillance",
    "misinformation",
    "disinformation",
    # Finance / economics
    "finance",
    "banking",
    "stock market",
    "investment",
    "investor",
    "interest rate",
    "inflation",
    "recession",
    "economic growth",
    "unemployment",
    "Federal Reserve",
    "central bank",
    "cryptocurrency",
    "bitcoin",
    "blockchain",
    "fraud",
    "money laundering",
    "payment",
    "credit card",
    "debt",
    "loan",
    "mortgage",
    "budget",
    "tax",
    "tariff",
    "trade",
    "earnings",
    "revenue",
    "profit",
    "loss",
    "bankruptcy",
    "merger",
    "acquisition",
    "layoff",
    # Personal emotions / relationships
    "emotion",
    "happiness",
    "sadness",
    "anger",
    "fear",
    "anxiety",
    "stress",
    "depression",
    "grief",
    "loneliness",
    "excitement",
    "surprise",
    "disappointment",
    "frustration",
    "hope",
    "trust",
    "betrayal",
    "empathy",
    "compassion",
    "love",
    "hate",
    "relationship",
    "friendship",
    "family",
    "conflict",
    "motivation",
    "burnout",
    "well-being",
    "mental health",
    "self-esteem",
    # Politics / government
    "politics",
    "government",
    "election",
    "candidate",
    "campaign",
    "voter",
    "voting",
    "ballot",
    "polling",
    "president",
    "prime minister",
    "Congress",
    "Senate",
    "parliament",
    "legislation",
    "regulation",
    "public policy",
    "political party",
    "democracy",
    "authoritarianism",
    "diplomacy",
    "sanction",
    "foreign policy",
    "national security",
    "geopolitics",
    "protest",
    "civil rights",
    "immigration",
    "war",
    "ceasefire",
    "peace agreement",
    # Sports
    "sports",
    "football",
    "soccer",
    "basketball",
    "baseball",
    "hockey",
    "tennis",
    "golf",
    "cricket",
    "rugby",
    "boxing",
    "wrestling",
    "Olympics",
    "World Cup",
    "Super Bowl",
    "playoffs",
    "championship",
    "tournament",
    "match",
    "game",
    "team",
    "player",
    "coach",
    "athlete",
    "injury",
    "trade deadline",
    "score",
    "record",
    "victory",
    "defeat",
    # Music / entertainment
    "music",
    "song",
    "album",
    "artist",
    "singer",
    "rapper",
    "band",
    "concert",
    "tour",
    "festival",
    "streaming",
    "Billboard",
    "Grammy",
    "record label",
    "music industry",
    "film",
    "movie",
    "television",
    "celebrity",
    "actor",
    "director",
    "box office",
    "award",
    "video game",
    "podcast",
    # Health / science
    "healthcare",
    "public health",
    "medicine",
    "disease",
    "virus",
    "pandemic",
    "vaccine",
    "treatment",
    "diagnosis",
    "clinical trial",
    "hospital",
    "patient",
    "pharmaceutical",
    "research",
    "scientist",
    "space",
    "NASA",
    "climate change",
    "global warming",
    "extreme weather",
    "wildfire",
    "hurricane",
    "earthquake",
    "flood",
    "renewable energy",
    # Business / workplace
    "business",
    "company",
    "startup",
    "enterprise",
    "customer",
    "employee",
    "workplace",
    "leadership",
    "management",
    "productivity",
    "remote work",
    "return to office",
    "hiring",
    "labor union",
    "strike",
    "compliance",
    "audit",
    "risk management",
    "insurance",
    "contract",
    "lawsuit",
    "settlement",
    # Society / culture
    "education",
    "school",
    "university",
    "student",
    "teacher",
    "housing",
    "homelessness",
    "crime",
    "law enforcement",
    "social media",
    "viral",
    "online community",
    "internet culture",
    "free speech",
    "censorship",
    "equality",
    "discrimination",
    "religion",
    "culture",
    "community",
    # Finance / markets
    "asset allocation",
    "portfolio diversification",
    "capital gains",
    "dividend yield",
    "market volatility",
    "liquidity",
    "credit risk",
    "default risk",
    "risk premium",
    "credit score",
    "net worth",
    "cash flow",
    "compound interest",
    "retirement planning",
    "financial independence",
    # Personal emotions / emotional states
    "resentment",
    "shame",
    "guilt",
    "envy",
    "jealousy",
    "regret",
    "nostalgia",
    "contentment",
    "relief",
    "despair",
    "indifference",
    "vulnerability",
    "emotional resilience",
    "emotional intelligence",
    "sense of belonging",
    # Philosophy / psychology
    "cognitive dissonance",
    "confirmation bias",
    "critical thinking",
    "moral dilemma",
    "free will",
    "determinism",
    "existentialism",
    "nihilism",
    "utilitarianism",
    "stoicism",
    "social identity",
    "groupthink",
    "attachment theory",
    "self-actualization",
    "meaning of life",
    # Economics
    "gross domestic product",
    "consumer confidence",
    "purchasing power",
    "cost of living",
    "income inequality",
    "wealth inequality",
    "labor market",
    "economic mobility",
    "fiscal policy",
    "monetary policy",
    "market competition",
    "supply and demand",
    "price elasticity",
    "opportunity cost",
    "behavioral economics",
# Ransomware / threat intel
    "ransomware",
    "nitrogen",
    "foxconn",
    "ESXi",
    "conti",
    "ALPHV",
    "blackcat",
    "RaaS",
    "double extortion",
    "supply chain",
    "data breach",
    "exfiltration",
    "payload",
    "loader",
    "YARA",
    "veeam",
    "watchtowr",
    "CVE",
    # OSINT / identity
    "OSINT",
    "data broker",
    "NPD",
    "national public data",
    "SSN",
    "dox",
    "facial recognition",
    "biometric",
    "SIM swap",
    "credential reset",
    "identity theft",
    "breach data",
    # InfoSec / general
    "zero-day",
    "exploit",
    "phishing",
    "malware",
    "APT",
    "threat actor",
    "lateral movement",
    "privilege escalation",
    "encryption",
    "decryption",
    "public key",
    "private key",
    "cryptographic",
]
]

REGEX_PATTERNS: RegexPatternDict = {
    PatternLabel.CVE_ID: r"CVE-\d{4}-\d{4,7}",
    PatternLabel.IP_ADDRESS: r"\b(?:\d{1,3}\.){3}\d{1,3}\b",
    PatternLabel.HASH_SHA256: r"\b[0-9a-fA-F]{64}\b",
    PatternLabel.HASH_MD5: r"\b[0-9a-fA-F]{32}\b",
    PatternLabel.DOMAIN: r"\b(?:[a-zA-Z0-9-]+\.)+(?:com|net|org|io|gov|edu|onion|xyz|co)\b",
    PatternLabel.EMAIL: r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
    PatternLabel.BTC_WALLET: r"\b[13][a-km-zA-HJ-NP-Z1-9]{25,34}\b",
    PatternLabel.RANSOM_AMOUNT: r"\$\s?\d[\d,]*(?:\.\d{2})?\s?(?:million|billion|M|B|k)?",
    PatternLabel.FILE_EXTENSION: r"\.\b(?:exe|dll|ps1|bat|sh|py|bin|enc|locked)\b",
    PatternLabel.DARK_WEB: r"\b\w+\.onion\b",
    PatternLabel.TELEGRAM_HANDLE: r"@[A-Za-z0-9_]{5,}",
    PatternLabel.PORT_NUMBER: r"\bport\s+(\d{2,5})\b",
    PatternLabel.TB_GB_DATA: r"\b\d+(?:\.\d+)?\s?(?:TB|GB|MB|terabyte|gigabyte)\b",
    PatternLabel.YEAR: r"\b20[12]\d\b",
    PatternLabel.PERCENTAGE: r"\b\d+(?:\.\d+)?%",
}
